name: gen_adversarial
channels:
  - pytorch
  - nvidia
  - gpytorch
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda==12.1
  # StyleGan dependencies for custom cuda ops
  - nvidia/label/cuda-12.1.0::cuda-toolkit
  - ninja
  # other stuff
  - einops
  - kornia
  - matplotlib
  - botorch  # bayesian optimization
  - pip
  - pip:
      - tqdm
      - pytorch-model-summary