name: gen_adversarial
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda==12.1
  - torchmetrics
  - einops
  - kornia
  - matplotlib
  - cupy
  - pkg-config
  - libjpeg-turbo>=2.1.4
  - opencv
  - numba==0.56.2  # solves import error!
  - pip
  - pip:
      - ffcv
      - tqdm
      - lmdb
      - tensorboardX
      - git+https://github.com/RobustBench/robustbench.git
      - scheduling_utils
      - pytorch-model-summary
      - wandb
      - torch-fidelity