name: adversarial_test
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda==12.1
  - torchmetrics
  - einops
  - kornia
  - matplotlib
  - pip
  - pip:
      - git+https://github.com/RobustBench/robustbench.git