name: adversarial_test
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda==12.1
  - torchmetrics
  - einops
  - kornia
  - matplotlib
  - pip
  - pip:
      - tqdm
      - lmdb
      - tensorboardX
      - git+https://github.com/RobustBench/robustbench.git
      - scheduling_utils