classifier_path: /add/your/path
autoencoder_path: /add/your/path

interpolation_alphas:
  - 0.000
  - 0.000
  - 0.001
  - 0.136
  - 0.131
  - 0.206
  - 0.179
  - 0.305
  - 0.347
  - 0.349
  - 0.465
  - 0.528
  - 0.551
  - 0.606
  - 0.681
  - 0.676
  - 0.834
  - 0.800
  - 0.938
  - 0.911
  - 1.000
  - 1.000
  - 1.000
  - 1.000
alpha_attenuation: 0.7
initial_noise_eps: 0.0
gaussian_blur_input: True

