classifier_path: /add/your/path
autoencoder_path: /add/your/path

interpolation_alphas:
  - 0.010
  - 0.038
  - 0.084
  - 0.146
  - 0.222
  - 0.309
  - 0.402
  - 0.500
  - 0.598
  - 0.691
  - 0.778
  - 0.854
  - 0.916
  - 0.962
  - 0.990
  - 1.000
alpha_attenuation: 0.7
initial_noise_eps: 4.0
gaussian_blur_input: False

