classifier_path: /add/your/path
autoencoder_path: /add/your/path

interpolation_alphas:
  - 1.000
  - 0.000
  - 0.000
  - 0.737
  - 0.000
  - 0.000
  - 0.834
  - 1.000
  - 0.261
  - 0.000
  - 0.205
  - 1.000
  - 0.908
  - 0.000
  - 0.268
  - 1.000
alpha_attenuation: 0.7
initial_noise_eps: 0.0
gaussian_blur_input: True

