classifier_path: /add/your/path
autoencoder_path: /add/your/path

interpolation_alphas:
  - 0.05
  - 0.11
  - 0.16
  - 0.22
  - 0.27
  - 0.33
  - 0.38
  - 0.44
  - 0.50
  - 0.55
  - 0.61
  - 0.66
  - 0.72
  - 0.77
  - 0.83
  - 0.88
  - 0.94
  - 1.00
alpha_attenuation: 1.0
initial_noise_eps: 4.0
gaussian_blur_input: False
