classifier_path: /add/your/path
autoencoder_path: /add/your/path

interpolation_alphas:
  - 0.492
  - 0.728
  - 0.058
  - 0.331
  - 0.246
  - 0.059
  - 0.068
  - 0.526
  - 0.646
  - 0.816
  - 0.548
  - 0.692
  - 0.309
  - 0.610
  - 0.729
  - 0.348
  - 0.728
  - 0.697
alpha_attenuation: 1.0
initial_noise_eps: 0.0
gaussian_blur_input: True
