classifier_path: /add/your/path
autoencoder_path: /add/your/path

interpolation_alphas:
  - 0.062
  - 0.125
  - 0.188
  - 0.250
  - 0.312
  - 0.375
  - 0.438
  - 0.500
  - 0.562
  - 0.625
  - 0.688
  - 0.750
  - 0.812
  - 0.875
  - 0.938
  - 1.000
alpha_attenuation: 0.7
initial_noise_eps: 2.0
gaussian_blur_input: False

