classifier_path: /add/your/path
autoencoder_path: /add/your/path

interpolation_alphas:
  - 0.00
  - 0.02
  - 0.04
  - 0.07
  - 0.10
  - 0.15
  - 0.20
  - 0.25
  - 0.31
  - 0.37
  - 0.43
  - 0.50
  - 0.57
  - 0.63
  - 0.69
  - 0.75
  - 0.80
  - 0.85
  - 0.90
  - 0.93
  - 0.96
  - 0.98
  - 1.00
  - 1.00
alpha_attenuation: 0.7
initial_noise_eps: 2.0
gaussian_blur_input: False

